[package]
name = "sy_infra"
version.workspace = true
edition.workspace = true

[dependencies]
sy_types.workspace = true
sy_config.workspace = true
sy_protocol.workspace = true
sy_api.workspace = true
sy_core.workspace = true
