[package]
name = "sy_cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sy_cli"
path = "src/main.rs"

[dependencies]
sy_types.workspace = true
sy_api.workspace = true
sy_core.workspace = true
sy_infra.workspace = true
sy_config.workspace = true
sy_tools.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
